[mongodb]
mongodb-dev.kesavatarun.in

[catalogue]
catalogue-dev.kesavatarun.in

[all:vars]
ansible_user=ec2-user #Give the instance username
ansible_ssh_private_key_file=./devops.pem #Give the instance passwords