[mongodb]
mongodb-dev.kesavatarun.in

[catalogue]
catalogue-dev.kesavatarun.in

[all:vars]
ansible_user="ec2-user" #Give the instance username
ansible_password="DevOps321" #Give the instance passwords
MONGODB_HOST=mongodb-dev.kesavatarun.in