- name: Create EC2 and R53 records with public IP address
  hosts: all #If not using inventory file we need to change host local to host all
  connection: local
  vars:
    sg_id: sg-0075bb69cff1075c4 #Should change everytime when ever new instance created
    ami_id: ami-0220d79f3f480ecf5 #Should change everytime when ever new instance created
    environment: dev #Should change accoringly; During development use dev, In production use qa and the environment variables
    instances: #List of the instances
      - mongodb
      - catalogue
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ environment }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ environment }}"
          Name: "{{ item }}-{{ environment }}"
      loop: "{{ intances }}"
      register: ec2_output

    - name: Print the Output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"
